<?php

/**
 * @file
 * Contains timeago.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function timeago_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the timeago module.
    case 'help.page.timeago':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Converts dynamic timestamps to a &#039;time ago&#039; format using jQuery with graceful degradation.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_library_info_alter().
 */
function timeago_library_info_alter(&$libraries, $extension) {
  if ($extension === 'timeago') {
    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $libraries["timeago"]["js"]["js/locales/jquery.timeago.{$langcode}.js"] = [];
  }
}
